### PR TITLE
[WIP] Script to monitor web resources

### PR DESCRIPTION
**Pull request by pchaigno**
Should replace one of Patrique's two functionalities.

Missing:
- [x] Manage the list of resources to monitor.
- [x] Actually monitor the resources.
- [x] Prevent huge resources from being added.
- [x] Remove huge resources from the list.
- [ ] Extract text from HTTP web resources.
- [ ] Manage concurrent accesses to the list.
- [ ] Allow huge resources and monitor the `last_edit_time` instead of the content.
- [x] Save the room where notifications should be sent.
- [x] Initialize the periodic check when the bot starts.
- [x] Allow URLs without the protocol (e.g., `github.com`).

### CODE REVIEW

**Comment by awailly** [comment]
I suggest to handle large files too, but using the last time modified in the header rather than performing a checksum on the downloaded data. You will save time and will not care about the size of the file. However the problem may appear if this header is not available.

**Comment by pchaigno** [comment]
> I suggest to handle large files too, but using the last time modified in the header rather than performing a checksum on the downloaded data. You will save time and will not care about the size of the file.

Nice idea :+1: I'll try to implement it in a second time.

> However the problem may appear if this header is not available.

I don't even know which type of large file we might want to monitor... PDFs?

**Comment by awailly** [comment]
The hardest use case I got was for an ISO file like debian.org/latest.iso.

**Comment by pchaigno** [comment]
Merging now. I'll handle the remaining tasks in other pull requests:
- Extract text from HTTP web resources: in a separate PR.
- Manage concurrent accesses to the list: we'll see if that's an issue in practice. It seems tricky to handle in Coffeescript.
- Allow huge resources and monitor the last_edit_time instead of the content: in a separate PR, will require code refactoring :/

**Pull request merged**
